name: .NET-Ubuntu

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v5
      with:
        submodules: recursive
    - name: Setup .NET
      uses: actions/setup-dotnet@v5
      with:
        dotnet-version: 8.0.x
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --no-restore
    - name: Install PuTTY for the tests
      run: sudo apt-get update && sudo apt-get install -y --no-install-recommends putty
    - name: Test
      run: dotnet test --no-build --verbosity normal
      env:
        SSHNET_AGENT_TESTS_REQUIRED: OpenSsh,Pageant,Server
    - uses: actions/upload-artifact@v5
      with:
        name: Sample-ubuntu
        path: |
          SshNet.Agent.Sample/bin/Debug/net8.0/*
